Check Attributes of the array In this task, you will check out the important attributes for a NumPy array Make a NumPy array also named array which consists of the first 10 natural numbers using the np.arange(1, 11) command (you will learn how to create such forms later on during the course). Check out its dimension and save it as dim. Reshape the above array into a (5, 2) array using the .reshape(5,2) on the previous array. You have to create a new array altogether for this operation so do not forget to assign to a new variable reshaped. Check out the new dimension and save it as new_dim. Print out dim and new_dim.

In [ ]:
import numpy as np
a = np.arange(1,11)      
print(a)
dim= a.ndim
print('The dimensions of array a is ',dim)
reshaped=a.reshape(5,2)
print(reshaped)
new_dim= reshaped.ndim
print('The dimensions of reshaped array  is ',new_dim)

[ 1  2  3  4  5  6  7  8  9 10]
The dimensions of array a is  1
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
The dimensions of reshaped array  is  2


Quiz: Arrays in NumPy

1.Are all the elements inside a NumPy ndarray of the same data type? YES

NO

2.By which method/attribute can you check the shape of NumPy array?

shape

ndim

3.Mathematically, what does the size attribute of NumPy ndarray equals to?

Product of the elements of shape attribute

Length of the NumPy ndarray

4.Which attribute is used to get the number of bytes in each element of the array? 
size
itemsize


Answers:
1-yes
2-shape
3-(product element of the shape attribute)
4- itemsize


Create your own array
In this task, you will practice creating new arrays of different types
 
Create an array out a 4x4 identity matrix with dtype float32 and save it in a variable named array
Print the array


In [ ]:
import numpy as np
array=np.eye(4,dtype='float32')
print(array)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Store marks and ID's as array In this task, you are going to store the marks and IDs of three students as NumPy arrays.
The marks are [20, 30, 40] and IDs are [0,2,4]. Store array for marks in a variable marks and the one for IDs in another variable ids. Display both marks and ids.


In [ ]:
marks =np.array([20,30,40])
ids=np.array([0,2,4])
print(marks)
print(ids)

[20 30 40]
[0 2 4]


Quiz:Creating Arrays with Numpy

1.What does np.arange(5) do?
Creates an array from 0-4
Creates an array from 1-5
2.Can you iterate over a NumPy ndarray using a for loop in the same manner as you do with Python lists? 
YES
NO
================================================================ 
3.What does the following code snippet display?
import numpy as np
 print(np.eye(5))
  5x5 Identity matrix
2x2 Identity matrix
3x3 Identity matrix
5x5 matrix consisting of 1s
=====================================================
 4.What is the output of the following code snippet?
import numpy as np 
a = np.arange(9).reshape(3,3)
 print(a[1,1]) 
2
3
4
5


Answers:
2-yes

In [ ]:
 np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:

print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
a = np.arange(9).reshape(3,3)
print(a)
print(a[1,1]) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


In this task, you will be filtering out complex elements from an array.
Create a (4,) array with values 3, 4.5, 3 + 5j and 0 using "np.array()". Save it to a variable array Create a boolean condition real to retain only a real number using .isreal(array). (Note: .isreal(array) returns a Boolean value which is True if the number inside the array is a real number and False otherwise) Now apply this Boolean condition i.e. real on array using Boolean indexing (explained in the topic) by array[real] and store it in variable real_array. Similarly, create a Boolean condition imag to retain only complex numbers which you can do it using .iscomplex(array). This time create an array imag_array which contains only complex numbers using the Boolean condition array[imag]


In [ ]:
import numpy as np
a = np.array([3, 4.5, 3 + 5j,0])
real=np.isreal(a)
print(real)
real_array=a[real]
print(real_array)
imag=np.iscomplex(a)
print(imag)
imag_array=a[imag]
print(imag_array)

[ True  True False  True]
[3. +0.j 4.5+0.j 0. +0.j]
[False False  True False]
[3.+5.j]


Buy/ Sell for maximum profit In this task, you will combine vectorization and aggregation methods to solve a BUY-SELL problem. You have a range of prices at 3 intervals of a day for 2 consecutive days and you can buy and sell only once. First, you will buy and then sell for the maximum profit.
Initialize an array prices = [[40, 35, 20], [21, 48, 70]]. Here, 40 is the market price during the first interval of the first day and 35 during the second interval and so on. Similarly, 21 is the price during the first half of the second day and 48 during the second half Flatten the array with the .flatten() method. This method will convert your 2-D array into a 1-D array and store it in variable prices. Find the minimum over the flattened array using np.min(), this will be your buying_price Also find the index of buying price by first converting the array into a list using list(array) and then use the .index(buying_price) attribute to pick the index of the buying price and store it in a variable index Create a new subset starting from the index (created in the previous step) till the end of the array and find the maximum value using np.max() in it. This will be your selling_price Find the difference between buying and selling price and save the same in variable profit


In [ ]:
import numpy as np
prices = np.array([[40, 35, 20], [21, 48, 70]])
print("2d array",prices)
p=prices.flatten()
print("flattened array",p)
buying_price=prices.min()
print("buying price(min value)",buying_price)
l=list(p)
print("array converted to list",list)
index=l.index(buying_price)
print("index of min valu",index)
l1=l[index:]
print(l1)
a=np.array(l1)
print(a)
selling_price=a.max()
print("selling price max value",selling_price)
profit=selling_price-buying_price
print("profit",profit)


2d array [[40 35 20]
 [21 48 70]]
flattened array [40 35 20 21 48 70]
buying price(min value) 20
array converted to list <class 'list'>
index of min valu 2
[20, 21, 48, 70]
[20 21 48 70]
selling price max value 70
profit 50


Create a random 5x5 matrix with the help of np.random.random((5,5)) and save it as z Calculate the minimum and maximum value with the help of .min() and .max() methods respectively for the 5x5 array. Save them as zmax and zmin for maximum and minimum respectively Now using the power of broadcasting subtract the minimum value from each element and divide by their range (maximum-minimum) to normalize. Save this normalized as z_norm Print the standardized array


In [ ]:
import numpy as np
np.random.seed(21)
z=np.random.random((5,5))
print("z=",z)
zmax=z.max()#zmax=np.max(z)---another way
zmin=z.min()
print(zmax,zmin)
z_norm=(z-zmin)/(zmax-zmin)
print("normalised array",z_norm)


z= [[0.04872488 0.28910966 0.72096635 0.02161625 0.20592277]
 [0.05077326 0.30227189 0.66391029 0.30811439 0.58359128]
 [0.06957095 0.86740448 0.13324052 0.17812466 0.49592955]
 [0.86369964 0.75894384 0.97048513 0.75930255 0.38425003]
 [0.40871833 0.71336043 0.27066977 0.85410287 0.91316397]]
0.9704851253491577 0.021616249915949792
normalised array [[0.02856942 0.28190767 0.73703555 0.         0.19423813]
 [0.03072817 0.29577917 0.67690496 0.3019365  0.59225784]
 [0.05053881 0.89136471 0.1176393  0.16494209 0.49987233]
 [0.88746023 0.77705951 1.         0.77743756 0.38217481]
 [0.40796162 0.72901978 0.26247412 0.87734633 0.93959001]]


**Quiz: Power of NumPy**

1.What gets printed?
import numpy as np
ary = np.array([1,2,3,5,8])
ary = ary + 1
print (ary[1]) 
1
2
3
5


In [ ]:
import numpy as np
ary = np.array([1,2,3,5,8])
ary = ary + 1
print("ary+1",ary)
print (ary[1]) 

ary+1 [2 3 4 6 9]
3


2.Which function returns its argument with a modified shape (array) and which one modifies the array itself?
reshape,resize
resize,reshape
reshape2,resize
all of the Mentioned
***Ans:***
reshape,resize# reshape makes copy, resize alters original array


3.The property by which NumPy can perform element-wise operation is called:
Vectorization
Broadcasting
***Ans:Vectorization***

4.If you have a NumPy array, in a variable bats, how would you access the data item at the 5th column, 2nd row?
bats[2,5]
bats(1,4)
Bats[1,4] 
bats[4,1]


In [ ]:
import numpy as np
bats = np.array([[1,2,3,5,8],[10,78,89,76,56]])
print(bats)
print(bats[1,4])

[[ 1  2  3  5  8]
 [10 78 89 76 56]]
56


Well, one way to find out the roots is to first calculate the discriminant and then solve for the roots. Using NumPy's .roots() the method you can calculate it in a single line. Now, this function can solve for any degree polynomial and since you will solve a quadratic equation, this function will take 3 arguments which represent the coefficients of the powers of x.
==========================================================
 Find roots of quadratic equation The quadratic equation that you will be solving is x^2 -4x + 4 = 0x 2 −4x+4=0 Make an array coeff to store the coefficients (1,-4, 4) of the quadratic equation. Pass this array coeff as argument to np.roots() method which will return the roots for the quadratic equation x^2 -4x + 4 = 0x 2 −4x+4=0. Save it as roots Print out roots to see your result


In [ ]:
import numpy as np
coeff=np.array([1,-4, 4])
roots=np.roots(coeff)
print(roots)


[2. 2.]


You will be converting the temperatures [0, 10, 25, 32, 80, 99.99] in Centigrades to Fahrenheit
Convert from centigrade to fahrenheit Store the given temperatures in an array centigrade_temps Define a function convert which takes one argument celsius(Centigrade temperature) that achieves the conversion from centigrade to Fahrenheit. The conversion formula is given, the body of convert must return the Fahrenheit temperature Use convert on centigrade_temps to convert Centigrade to Fahrenheit scale and store it as fahrenheit_temps


In [ ]:
centigrade_temps= [0, 10, 25, 32, 80, 99.99]
fahrenheit_temps=[]
def convert(celsius):
  for i in centigrade_temps:
    f = float((i * 1.8) + 32)
    fahrenheit_temps.append(f)

 
convert(centigrade_temps) 
fahrenheit_temps_arr=np.array(fahrenheit_temps) 
print(fahrenheit_temps)
print(fahrenheit_temps_arr)


[32.0, 50.0, 77.0, 89.6, 176.0, 211.982]
[ 32.     50.     77.     89.6   176.    211.982]


In [ ]:
"""centigrade_temps= [0, 10, 25, 32, 80, 99.99]
def convert(celsius):
  for i in centigrade_temps
  f = float(i * 1.8) + 32
  return f
fahrenheit_temps=[]
fahrenheit_temps=f.append()
traial

"""
centigrade_temps = np.array([0, 10, 25, 32, 80, 99.99])
x=[]
# function for conversion
def convert(celsius):
    for i in np.nditer(celsius):
        F=(i*9/5)+32
        x.append(F)
    
convert(centigrade_temps)
# display fahrehheit temperatures
fahrenheit_temps=np.array(x)

print(fahrenheit_temps)



[ 32.     50.     77.     89.6   176.    211.982]


 
Solve system of equations You have a system of a linear equation Ax = bAx=b where 
A = [ 2  1  2]
 [ 3  0  1]
 [ 1  1 -1]
 
Define variables A and b as shown above Use .linalg.solve() to solve for the system of linear equation. Go through the documentation for numpy.linalg.solve to better understand its behaviour. Save this result as x Check that your solution is correct with the function np.allclose(np.dot(A,x), b) and save it to a variable check. Print out check to see if it is True or else try again!


In [ ]:

import numpy as np
A = np.array([[2,1,2], [3,0,1],[1,1,-1]])
print ("A=",A)
B= np.array([-3,5,2]) #b=np.array([[-3],[5],[2]])
print("B=",B)
b=B.reshape(3,1) #not required if b=np.array([[-3],[5],[2]]) used
print("b=",b)
x = np.linalg.solve(A, b)
print("x=",x)
check=np.allclose(np.dot(A,x), b) 
print("check",check)

A= [[ 2  1  2]
 [ 3  0  1]
 [ 1  1 -1]]
B= [-3  5  2]
b= [[-3]
 [ 5]
 [ 2]]
x= [[ 2.5]
 [-3. ]
 [-2.5]]
check True


Find a 3x3 Non Singular Matrix Take a pen and paper for this task to find a 3×3nonsingular matrix A satisfying 3A=A^2+AB, where 
B=[2,0,-1]
  [0,2,-1]
  [-1,0,1]

Find a non singular matrix Assume that A is a non-singular matrix Resolve the equation 3A = A^2 + AB until it reduces to a simpler form for you to carry out simple array addition. Array A should be coming as A = 3I - B where I is the Identity matrix Initialize array B using np.array() and I using np.identity() Save resultant array as A which is given mathematically by A = 3I - B.Display matrix A
 


In [ ]:
import numpy as np
# initialize array B and Identity matrix
B=np.array([[2,0,-1],[0,2,-1],[-1,0,1]])
I=np.eye(3)#eye prints identity matrix
print(I)

#print(B,I)
# calculate result
A=3*I-B
print(A)
# Code ends here

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 1.]
 [0. 1. 1.]
 [1. 0. 2.]]


## PROJECT

Make sense of Census
Instructions :
Step 1: In this first task, we will load the data to a numpy array and add a new record to it.
The path to the data set has been stored in the variable named path
Load the dataset and store it in a variable called data using np.genfromtxt()

  Example of genfromtxt function


data_file='file.csv' # path for the file
data=np.genfromtxt(data_file, delimiter=",", skip_header=1)

print("\nData: \n\n", data)

print("\nType of data: \n\n", type(data))

Output
Data: 

[[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

Type of data: 

 <class 'numpy.ndarray'>


Note:
The parameter 'delimiter="," ' is set because the file that we are opening has extension CSV(Comma Separated Values)
The parameter 'skip_header=1' is set because the first row of the data(which is called header) contains string values but in our numpy array we need only integers(Remember numpy array can only store data of a single data type)

Append 'new_record' (given) to 'data' using "np.concatenate()" and store the new array in a variable called census

The shape of data should be (1000, 8) and that of census should be (1001,8).

Step 2: We often associate the potential of a country based on the age distribution of the people residing there. We too want to do a simple analysis of the age distribution
Instructions :
Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.
Find the max age and store it in a variable called 'max_age'.
Find the min age and store it in a variable called 'min_age'.
Find the mean of the age and store it in a variable called 'age_mean'.
Find the standard deviation of the age and store it in a variable called 'age_std'.
Ponder whether based on the above statistics, would you classify the country as 'young' or 'old'?

max_age should be 90.
min_age should be 17.
age_mean, rounded off to two places, should be 38.06.
age_std, rounded off to two places, should be13.34.

Step 3: The constitution of the country tries it's best to ensure that people of all races are able to live harmoniously. Let's check the country's race distribution to identify the minorities so that the government can help them.
Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)
Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively
Find out which is the race with the minimum no. of citizens
Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

minority_race should be 3.

Step 4: As per the new govt. policy, all citizens above age 60 should not be made to work more than 25 hours per week. Let us look at the data and see if that policy is followed.
Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)
Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'
Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'
Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.
Print 'avg_working_hours' and see if the govt. policy is followed.

working_hours_sum should be 1917.
avg_working_hours, rounded off to two places, should be 31.43.

Step 5: Our parents have repeatedly told us that we need to study well in order to get a good(read: higher-paying) job. Let's see whether the higher educated people have better pay in general.
Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.
Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

Note: - Since income is a binary variable, mean() here represents the percentage of ppl having annual income higher than 50K. - You could have used "mean()" function to solve the task 'Young Country? Old Country?' as well.

Compare 'avg_pay_high' and 'avg_pay_low' and see whether there is truth in better education leads to better pay

Test Cases: The correct value in 'avg_pay_high' should be 0.43 when rounded upto 2 decimal places. The correct value in 'avg_pay_low' should be 0.14 when rounded upto 2 decimal places.




In [ ]:
from google.colab import files
uploaded = files.upload()

Saving census.csv to census.csv


step1

In [ ]:
import numpy as np
data_file='census.csv' # path for the file
data=np.genfromtxt(data_file, delimiter=",", skip_header=1)

print("\nData: \n\n", data)

print("\nType of data: \n\n", type(data))



Data: 

 [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]

Type of data: 

 <class 'numpy.ndarray'>


In [ ]:
import numpy as np
new_record=np.array([[56,12,4,1,0,0,35,0]])  #new_record=[[56,12,4,1,0,0,35,0]]
census=np.concatenate((data,new_record),axis=0)
print("shape of data",np.shape(data))
print("shape of census",np.shape(census))

shape of data (1000, 8)
shape of census (1001, 8)


step 2

In [ ]:
age=census[:,0]
print(age)

[39. 50. 38. ... 40. 39. 56.]


In [ ]:
max_age=np.max(age) #age.max()
print("max age",max_age)

max age 90.0


In [ ]:
min_age=np.min(age)
print("min age",min_age)


min age 17.0


In [ ]:
age_mean=np.mean(age)
print("age mean",age_mean)
round(age_mean,2)

age mean 38.06893106893107


38.07

In [ ]:

age_std=np.std(age)
print("age std deviation",age_std)
round(age_std,2)

age std deviation 13.348186007340368


13.35

Step 3

In [ ]:
race=census[:,2]
print(race)

[4. 4. 4. ... 4. 4. 4.]


In [ ]:
race_0=[]
race_1=[]
race_2=[]
race_3=[]
race_4=[]
for i in range(len(race)):
    if race[i] == 0:
        race_0.append(race[i])
    elif race[i] == 1:
        race_1.append(race[i])
    elif race[i] == 2:
        race_2.append(race[i])
    elif race[i] == 3:
        race_3.append(race[i]) 
    elif race[i] == 4:
        race_4.append(race[i])       

print(race_0)   
print(race_1) 
print(race_2) 
print(race_3) 
print(race_4)     

[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
[2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]
[3.0, 3.0, 3.0, 3.0, 3.0, 3.0]
[4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 4.0, 

In [ ]:
#Subsetting easy way very very vey imp


race_0=census[census[:,2]==0]
race_1=census[census[:,2]==1]
race_2=census[census[:,2]==2]
race_3=census[census[:,2]==3]
race_4=census[census[:,2]==4]
print(race_0)   
print(race_1) 
print(race_2) 
print(race_3) 
print(race_4)  

[[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]
[[3.000e+01 1.300e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [4.000e+01 1.100e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [5.400e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 6.000e+01
  1.000e+00]
 [3.000e+01 9.000e+00 1.000e+00 0.000e+00 0.000e+00 1.573e+03 3.500e+01
  0.000e+00]
 [4.900e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [3.300e+01 1.300e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [4.400e+01 1.400e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [2.800e+01 9.000e+00 1.000e+00 0.000e+00 0.000e+00 0.

In [ ]:
len_0=len(race_0)
len_1=len(race_1)
len_2=len(race_2)
len_3=len(race_3)
len_4=len(race_4)
print("race with value 0:",len_0)
print("race with value 1:",len_1)
print("race with value 2:",len_2)
print("race with value 3:",len_3)
print("race with value 4:",len_4)

race with value 0: 10
race with value 1: 27
race with value 2: 110
race with value 3: 6
race with value 4: 848


In [ ]:
x=[len_0,len_1,len_2,len_3,len_4]
y=min(x)
z=x.index(y)
print("minimum no of citizens",y)
minority_race=z
print("minority_race:",minority_race)
#minority_race=x.index(min(x))


minimum no of citizens 6
minority_race: 3


Step 4

In [ ]:

senior_citizens=census[census[:,0]>60]
print(senior_citizens)


[[7.9000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.7000e+01 6.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+00 0.0000e+00]
 [7.6000e+01 1.4000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 1.0000e+00]
 [6.1000e+01 9.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [7.0000e+01 1.0000e+01 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [6.4000e+01 7.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 2.1790e+03
  4.0000e+01 0.0000e+00]
 [7.1000e+01 1.0000e+01 2.0000e+00 1.0000e+00 0.0000e+00 1.8160e+03
  2.0000e+00 0.0000e+00]
 [6.8000e+01 2.0000e+00 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.6000e+01 1.1000e+01 4.0000e+00 0.0000e+00 0.0000e+00 0.0000e+00
  2.0000e+01 0.0000e+00]
 [6.4000e+01 2.0000e+00 4.0000e+00 1.0000e+00 0.0000e+00 0.0000e+00
  4.0000e+01 0.0000e+00]
 [9.0000e+01 9.0000e+00 2.0000e+00 1.0000e+00 0.0000e+00 2.2060e+03
  

In [ ]:


working_hours_sum=senior_citizens.sum(axis=0)[6]
print(working_hours_sum)


1917.0


In [ ]:
senior_citizens_len=len(senior_citizens)
print(senior_citizens_len)

61


In [ ]:
avg_working_hours=float(working_hours_sum/senior_citizens_len)
print(round(avg_working_hours,2))

31.43


Step 5

In [ ]:
high=census[census[:,1]>10]
low=census[census[:,1]<=10]
avg_pay_high=high[:,7].mean()
avg_pay_low=low[:,7].mean()
print(avg_pay_high)
print(avg_pay_low)

0.4268292682926829
0.13670133729569092
